development:
  adapter: postgresql
  database: user_submission_development
  username: user_submission
  password:

# host: localhost
# port: 5432

test:
  adapter: postgresql
  database: user_submission_test
  username: user_submission
  password:

production:
  adapter: postgresql
  database: user_submission_production
  username: user_submission
  password:
